// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFuD-SJa3TqHgz2vfDrNuQW4XDiXU0Xh4',
    appId: '1:130645690885:web:2dfac0fddba227fd66aa6c',
    messagingSenderId: '130645690885',
    projectId: 'chdt-63f61',
    authDomain: 'chdt-63f61.firebaseapp.com',
    databaseURL: 'https://chdt-63f61-default-rtdb.firebaseio.com',
    storageBucket: 'chdt-63f61.appspot.com', // ✅ ĐÃ SỬA
    measurementId: 'G-KXJL8HP9S5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXibedUzr8GpaEpTlwIa0wa2SQ-XB9jEA',
    appId: '1:130645690885:android:5a58eef12d91967266aa6c',
    messagingSenderId: '130645690885',
    projectId: 'chdt-63f61',
    databaseURL: 'https://chdt-63f61-default-rtdb.firebaseio.com',
    storageBucket: 'chdt-63f61.appspot.com', // ✅ ĐÃ SỬA
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFuD-SJa3TqHgz2vfDrNuQW4XDiXU0Xh4',
    appId: '1:130645690885:web:d7ca352c978b7f1e66aa6c',
    messagingSenderId: '130645690885',
    projectId: 'chdt-63f61',
    authDomain: 'chdt-63f61.firebaseapp.com',
    databaseURL: 'https://chdt-63f61-default-rtdb.firebaseio.com',
    storageBucket: 'chdt-63f61.appspot.com', // ✅ ĐÃ SỬA
    measurementId: 'G-Q0SKFP627B',
  );
}
